### ISSUE TITLE
pbm with metronome wallet

### ISSUE THREAD

**Issue by fredb591** [autonomoussoftware/documentation#27]
Hello,
I did not receive my met, one failed transaction and one is blocked since two days ???
What's happen ??? I don't understand, where is my ethereum ?? 
Thank you for answering me
Fred
![metronome](https://user-images.githubusercontent.com/40617671/41948936-705d4f4c-79bf-11e8-8140-525483cb175c.jpg)

**Comment by gabmontes** [comment]
@fredb591 as per the screenshot you sent, neither transactions are blocked. One succeeded and the other one failed. Your ETH and your MET are in your wallet.
