### ISSUE TITLE
Error in Metronome Auction

### ISSUE THREAD

**Issue by rsostrow91** [autonomoussoftware/documentation#32]
I will leave a new issue here ***EVERY DAY*** until Issue **#25** below is answered to my satisfaction. Thank you for your attention.

1. You owe me ***MET*** (details below, click->**#25**) at around $2.00/per.
2. You owe me ***ETH*** (details below, click->**#25**) at the current price.
3. You owe me ***an explanation and a fix*** for the ***error messages*** I received. (details below, click->**#25**)

**Comment by jgarzik** [comment]
Closing, duplicate issue.  Please do not file duplicate issues.
